from mesa import Agent
from enum import Enum
DEBUG = False

# ---------------------------------------------------------------
class Infra(Agent):
    """
    Base class for all infrastructure components

    Attributes
    __________
    vehicle_count : int
        the number of vehicles that are currently in/on (or totally generated/removed by)
        this infrastructure component

    length : float
        the length in meters
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown'):
        super().__init__(unique_id, model)
        self.length = length
        self.name = name
        self.road_name = road_name
        self.vehicle_count = 0

    def step(self):
        pass

    def __str__(self):
        return type(self).__name__ + str(self.unique_id)


# ---------------------------------------------------------------
class Bridge(Infra):
    """
    Creates delay time

    Attributes
    __________
    condition:
        condition of the bridge

    delay_time: int
        the delay (in ticks) caused by this bridge
    ...

    """

    def __init__(self, unique_id, model, length=0,
                 name='Unknown', road_name='Unknown', condition='Unknown', lat=0, lon=0):
        super().__init__(unique_id, model, length, name, road_name)

        self.condition = condition
        self.lat = lat
        self.lon = lon

        # TODO
        self.delay_time = 0
        self.broken = self.set_broken()
        # print(self.delay_time)

    def set_broken(self):
        """Determine if the bridge is broken based on its condition and the corresponding probabilities"""
        broken = False
        if self.condition == 'A':
            broken = self.model.cat_a > 0 and self.model.random.randint(1, 100) <= self.model.cat_a
        elif self.condition == 'B':
            broken = self.model.cat_b > 0 and self.model.random.randint(1, 100) <= self.model.cat_b
        elif self.condition == 'C':
            broken = self.model.cat_c > 0 and self.model.random.randint(1, 100) <= self.model.cat_c
        elif self.condition == 'D':
            broken = self.model.cat_d > 0 and self.model.random.randint(1, 100) <= self.model.cat_d
        return broken

    def get_delay_time(self):
        """
        Get the delay time caused by this bridge if it is broken on its condition and length
        """
        if self.broken:
            if self.length < 10:
                self.delay_time = self.model.random.uniform(10,20) # delay time between 10 and 20 minutes for short bridges
            elif self.length < 50:
                self.delay_time = self.model.random.uniform(15,60) # delay time between 30 and 60 minutes for long bridges
            elif self.length < 200:
                self.delay_time = self.model.random.uniform(45,90) # delay time between 45 and 90 minutes for very long bridges
            else:
                self.delay_time = self.model.random.triangular(60, 120, 240) # delay time between 1 and 4 hours for extremely long bridges
        else:
            self.delay_time = 0

        return self.delay_time


# ---------------------------------------------------------------
class Link(Infra):
    pass


# ---------------------------------------------------------------
class Sink(Infra):
    """
    Sink removes vehicles

    Attributes
    __________
    vehicle_removed_toggle: bool
        toggles each time when a vehicle is removed
    ...

    """
    vehicle_removed_toggle = False

    def remove(self, vehicle):
        self.model.schedule.remove(vehicle)
        self.model.record_completed_trip(vehicle)
        self.vehicle_removed_toggle = not self.vehicle_removed_toggle
        print(str(self) + ' REMOVE ' + str(vehicle))


# ---------------------------------------------------------------

class Source(Infra):
    """
    Source generates vehicles

    Class Attributes:
    -----------------
    truck_counter : int
        the number of trucks generated by ALL sources. Used as Truck ID!

    Attributes
    __________
    generation_frequency: int
        the frequency (the number of ticks) by which a truck is generated

    vehicle_generated_flag: bool
        True when a Truck is generated in this tick; False otherwise
    ...

    """

    truck_counter = 0
    generation_frequency = 5
    vehicle_generated_flag = False

    def step(self):
        if self.model.schedule.steps % self.generation_frequency == 0:
            self.generate_truck()
        else:
            self.vehicle_generated_flag = False

    def generate_truck(self):
        """
        Generates a truck, sets its path, increases the global and local counters
        """
        try:
            agent = Vehicle('Truck' + str(Source.truck_counter), self.model, self)
            if agent:
                self.model.schedule.add(agent)
                agent.set_path()
                Source.truck_counter += 1
                self.vehicle_count += 1
                self.vehicle_generated_flag = True
                print(str(self) + " GENERATE " + str(agent))
        except Exception as e:
            print("Oops!", e.__class__, "occurred.")


# ---------------------------------------------------------------
class SourceSink(Source, Sink):
    """
    Generates and removes trucks
    """
    pass


# ---------------------------------------------------------------
class Vehicle(Agent):
    """

    Attributes
    __________
    speed: float
        speed in meter per minute (m/min)

    step_time: int
        the number of minutes (or seconds) a tick represents
        Used as a base to change unites

    state: Enum (DRIVE | WAIT)
        state of the vehicle

    location: Infra
        reference to the Infra where the vehicle is located

    location_offset: float
        the location offset in meters relative to the starting point of
        the Infra, which has a certain length
        i.e. location_offset < length

    path_ids: Series
        the whole path (origin and destination) where the vehicle shall drive
        It consists the Infras' uniques IDs in a sequential order

    location_index: int
        a pointer to the current Infra in "path_ids" (above)
        i.e. the id of self.location is self.path_ids[self.location_index]

    waiting_time: int
        the time the vehicle needs to wait

    generated_at_step: int
        the timestamp (number of ticks) that the vehicle is generated

    removed_at_step: int
        the timestamp (number of ticks) that the vehicle is removed
    ...

    """

    # 48 km/h translated into meter per min
    speed = 48 * 1000 / 60
    # One tick represents 1 minute
    step_time = 1

    class State(Enum):
        DRIVE = 1
        WAIT = 2

    def __init__(self, unique_id, model, generated_by,
                 location_offset=0, path_ids=None):
        super().__init__(unique_id, model)
        self.generated_by = generated_by
        self.generated_at_step = model.schedule.steps
        self.location = generated_by
        self.location_offset = location_offset
        self.pos = generated_by.pos
        self.path_ids = path_ids
        # default values
        self.state = Vehicle.State.DRIVE
        self.location_index = 0
        self.waiting_time = 0
        self.waited_at = None
        self.removed_at_step = None
        # variables to track delay time
        self.delay_time = 0


    def __str__(self):
        return "Vehicle" + str(self.unique_id) + \
               " +" + str(self.generated_at_step) + " -" + str(self.removed_at_step) + \
               " " + str(self.state) + '(' + str(self.waiting_time) + ') ' + \
               str(self.location) + '(' + str(self.location.vehicle_count) + ') ' + str(self.location_offset)

    def set_path(self):
        """
        Set the origin destination path of the vehicle
        """
        self.path_ids = self.model.get_random_route(self.generated_by.unique_id)

    def step(self):
        """
        Vehicle waits or drives at each step
        """
        if self.state == Vehicle.State.WAIT:
            self.waiting_time = max(self.waiting_time - 1, 0)
            if self.waiting_time == 0:
                self.waited_at = self.location
                self.state = Vehicle.State.DRIVE

        if self.state == Vehicle.State.DRIVE:
            self.drive()

        """
        To print the vehicle trajectory at each step
        """
        # print(self)

    def drive(self):

        # the distance that vehicle drives in a tick
        # speed is global now: can change to instance object when individual speed is needed
        distance = Vehicle.speed * Vehicle.step_time
        distance_rest = self.location_offset + distance - self.location.length

        if distance_rest > 0:
            # go to the next object
            self.drive_to_next(distance_rest)
        else:
            # remain on the same object
            self.location_offset += distance

    def drive_to_next(self, distance):
        """
        vehicle shall move to the next object with the given distance
        """
        self.location_index += 1
        next_id = self.path_ids[self.location_index]
        next_infra = self.model.schedule._agents[next_id]  # Access to protected member _agents

        if isinstance(next_infra, Sink):
            # arrive at the sink
            self.arrive_at_next(next_infra, 0)
            self.removed_at_step = self.model.schedule.steps
            self.location.remove(self)
            return
        elif isinstance(next_infra, Bridge):
            # if next object is also a bridge, check if it has the same length as the current one.
            if DEBUG:
                print(f"Vehicle {self.unique_id} arrives at bridge {next_infra.unique_id} with condition {next_infra.condition} and length {next_infra.length}.")
            alternative_bridges = [next_infra]
            while self.location_index + 1 < len(self.path_ids):
                next_infra_neighbor = self.model.schedule._agents[self.path_ids[self.location_index + 1]]
                # if isinstance(next_infra_neighbor, Bridge) and next_infra_neighbor.length == next_infra.length:
                if isinstance(next_infra_neighbor, Bridge) and self.bridges_are_interchangeable(next_infra, next_infra_neighbor, tolerance=0.00005):
                    # if the next bridge has the same length, we can skip the waiting time of the current bridge
                    if DEBUG:
                        print(f"Vehicle {self.unique_id} also arrives at bridge {next_infra_neighbor.unique_id} with condition {next_infra_neighbor.condition} and length {next_infra_neighbor.length}.")
                    alternative_bridges.append(next_infra_neighbor)
                    self.location_index += 1
                    next_infra = next_infra_neighbor
                else:
                    break
            # if bridges all have the same condition, choose one, otherwise chose the one which is not broken
            best_brige = alternative_bridges[0]
            best_delay = best_brige.get_delay_time()
            best_time = best_delay + best_brige.length / Vehicle.speed * Vehicle.step_time
            if DEBUG:
                print(f"Vehicle {self.unique_id} checks bridge {best_brige.unique_id} with condition {best_brige.condition} and length {best_brige.length}. Delay time: {best_delay} minutes. Total time: {best_time} minutes.")
            for bridge in alternative_bridges[1:]:
                delay = bridge.get_delay_time()
                time = delay + bridge.length / Vehicle.speed * Vehicle.step_time

                if DEBUG:
                    print(f"Vehicle {self.unique_id} checks bridge {bridge.unique_id} with condition {bridge.condition} and length {bridge.length}. Delay time: {delay} minutes. Total time: {time} minutes.")
                if time < best_time:
                    best_brige = bridge
                    best_delay = delay
                    best_time = time
            if DEBUG:
                print(f"Vehicle {self.unique_id} chooses bridge {best_brige.unique_id} with condition {best_brige.condition} and length {best_brige.length}. Delay time: {best_delay} minutes. Total time: {best_time} minutes.")
            self.waiting_time = best_delay
            next_infra = best_brige
            if DEBUG and self.waiting_time > 0:
                print(f"Vehicle {self.unique_id} has to wait for {self.waiting_time} minutes at bridge {next_infra.unique_id} with condition {next_infra.condition} and length {next_infra.length}. Total time: {best_time} minutes.")
            
            if self.waiting_time > 0:
                # arrive at the bridge and wait
                self.delay_time += self.waiting_time
                self.arrive_at_next(next_infra, 0)
                self.state = Vehicle.State.WAIT

                event = {
                    "truck_id": self.unique_id,
                    "bridge_id": self.location.unique_id,
                    "bridge_condition": self.location.condition,
                    "bridge_length": self.location.length,
                    "start_time": self.model.schedule.steps,
                    "end_time": self.model.schedule.steps + self.waiting_time,
                    "wait_duration": self.waiting_time,
                }
                self.model.wait_events.append(event)
                return
            # else, continue driving

        if next_infra.length > distance:
            # stay on this object:
            self.arrive_at_next(next_infra, distance)
        else:
            # drive to next object:
            self.drive_to_next(distance - next_infra.length)

    def arrive_at_next(self, next_infra, location_offset):
        """
        Arrive at next_infra with the given location_offset
        """
        self.location.vehicle_count -= 1
        self.location = next_infra
        self.location_offset = location_offset
        self.location.vehicle_count += 1

    def bridges_are_interchangeable(self, bridge1, bridge2, tolerance=0.00005):
        """
        Check if two bridges are interchangeable for the vehicle, which means they are appriximately at the same location and thus both go to the same destination point.
        """
        return abs(bridge1.lat - bridge2.lat) < tolerance and abs(bridge1.lon - bridge2.lon) < tolerance

# EOF -----------------------------------------------------------


